[general]
name = "json-cat"
version = "0.1.0"

[build]
output = "json_cat.out"
opt_level = "separated"
files = [
    "json_cat.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
# path = "../../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-app"
version = "*"
# path = "../../fixlang-minilib-app"
git = { url = "https://github.com/pt9999/fixlang-minilib-app.git" }

[[dependencies]]
name = "minilib-json"
version = "*"
# path = "../../fixlang-minilib-json"
git = { url = "https://github.com/pt9999/fixlang-minilib-json.git" }
