[general]
name = "minilib-collection"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
    "lib/collection/deque.fix",
    "lib/collection/ordered_map.fix",
    "lib/collection/rbtree.fix",
    "lib/collection/tree_map.fix",
    "lib/collection/tree_set.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/collection/deque_test.fix",
    "tests/collection/ordered_map_test.fix",
    "tests/collection/rbtree_test.fix",
    "tests/collection/tree_map_test.fix",
    "tests/collection/tree_set_test.fix",
    "tests/testing/test_util_array.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../fixlang-minilib-common"


[[dependencies]]
name = "hashmap"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }