[general]
name = "minilib-common"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
    "lib/common/common.fix",
    "lib/common/random_ex.fix",
    "lib/common/time_ex.fix",
    "lib/testing/unit_test.fix",
    "lib/text/string_ex.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/text/string_ex_test.fix",
    "tests/common/random_ex_test.fix",
]

[[dependencies]]
name = "character"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-character.git" }


[[dependencies]]
name = "hashmap"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }

[[dependencies]]
name = "time"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-time.git" }

[[dependencies]]
name = "random"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }