[general]
name = "calc-pi"
version = "0.1.0"

[build]
output = "calc_pi.out"
opt_level = "separated"
files = [
    "calc_pi.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../../fixlang-minilib-common"
# git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-app"
version = "*"
path = "../../fixlang-minilib-app"
# git = { url = "https://github.com/pt9999/fixlang-minilib-app.git" }

[[dependencies]]
name = "minilib-math"
version = "*"
path = "../../fixlang-minilib-math"
# git = { url = "https://github.com/pt9999/fixlang-minilib-math.git" }
