[general]
name = "minilib"
version = "0.1.0"
authors = ["pt9999 <18054486+pt9999@users.noreply.github.com>"]
description = "Minilib is a small library for FixLang."
license = "MIT"

[build]
files = []
