[[projects]]
name = "minilib-app"
git = "https://github.com/pt9999/fixlang-minilib-app.git"

[[projects]]
name = "minilib-binary"
git = "https://github.com/pt9999/fixlang-minilib-binary.git"

[[projects]]
name = "minilib-collection"
git = "https://github.com/pt9999/fixlang-minilib-collection.git"

[[projects]]
name = "minilib-common"
git = "https://github.com/pt9999/fixlang-minilib-common.git"

[[projects]]
name = "minilib-comonad"
git = "https://github.com/pt9999/fixlang-minilib-comonad.git"

[[projects]]
name = "minilib-crypto"
git = "https://github.com/pt9999/fixlang-minilib-crypto.git"

[[projects]]
name = "minilib-examples"
git = "https://github.com/pt9999/fixlang-minilib-examples.git"

[[projects]]
name = "minilib-io"
git = "https://github.com/pt9999/fixlang-minilib-io.git"

[[projects]]
name = "minilib-json"
git = "https://github.com/pt9999/fixlang-minilib-json.git"

[[projects]]
name = "minilib-math"
git = "https://github.com/pt9999/fixlang-minilib-math.git"

[[projects]]
name = "minilib-media"
git = "https://github.com/pt9999/fixlang-minilib-media.git"

[[projects]]
name = "minilib-monad"
git = "https://github.com/pt9999/fixlang-minilib-monad.git"

[[projects]]
name = "minilib-net"
git = "https://github.com/pt9999/fixlang-minilib-net.git"

[[projects]]
name = "minilib-text"
git = "https://github.com/pt9999/fixlang-minilib-text.git"

[[projects]]
name = "minilib-thread"
git = "https://github.com/pt9999/fixlang-minilib-thread.git"

[[projects]]
name = "minilib-xml"
git = "https://github.com/pt9999/fixlang-minilib-xml.git"

