[[projects]]
name = "minilib-common"
git = "https://github.com/pt9999/fixlang-minilib-common.git"
description = "Minilib: Common modules (UnitTest, Assertion, String extension etc.)"

[[projects]]
name = "minilib-text"
git = "https://github.com/pt9999/fixlang-minilib-text.git"
description = "Minilib: Text handling (SimpleParser, Unicode etc.)"

[[projects]]
name = "minilib-binary"
git = "https://github.com/pt9999/fixlang-minilib-binary.git"
description = "Minilib: Binary handling (ByteBuffer, BASE64, Hex string)"

[[projects]]
name = "minilib-io"
git = "https://github.com/pt9999/fixlang-minilib-io.git"
description = "Minilib: IO operations (File System, Platform Info etc.)"

[[projects]]
name = "minilib-collection"
git = "https://github.com/pt9999/fixlang-minilib-collection.git"
description = "Minilib: Collections (TreeSet, TreeMap, OrderedMap, Deque etc.)"

[[projects]]
name = "minilib-monad"
git = "https://github.com/pt9999/fixlang-minilib-monad.git"
description = "Minilib: Monads (State/Reader/Writer monad, Monad transformer etc.)"

[[projects]]
name = "minilib-comonad"
git = "https://github.com/pt9999/fixlang-minilib-comonad.git"
description = "Minilib: Comonads (Env/Traced comonad etc.)"

[[projects]]
name = "minilib-random"
git = "https://github.com/pt9999/fixlang-minilib-random.git"
description = "Minilib: Random monad etc."

[[projects]]
name = "minilib-thread"
git = "https://github.com/pt9999/fixlang-minilib-thread.git"
description = "Minilib: Multithreading (Task pool, Channel etc.)"

[[projects]]
name = "minilib-net"
git = "https://github.com/pt9999/fixlang-minilib-net.git"
description = "Minilib: Networks (TCP/IP, HTTP etc.)"

[[projects]]
name = "minilib-math"
git = "https://github.com/pt9999/fixlang-minilib-math.git"
description = "Minilib: Math (Complex number, BigInt, BigFloat, Algebra etc.)"

[[projects]]
name = "minilib-crypto"
git = "https://github.com/pt9999/fixlang-minilib-crypto.git"
description = "Minilib: Cryptography (AES, SHA-1, SHA-256, HMAC etc.)"

[[projects]]
name = "minilib-app"
git = "https://github.com/pt9999/fixlang-minilib-app.git"
description = "Minilib: Application Support (CommandLine parser etc.)"

[[projects]]
name = "minilib-media"
git = "https://github.com/pt9999/fixlang-minilib-media.git"
description = "Minilib: Multimedia (PNG image etc.)"

[[projects]]
name = "minilib-json"
git = "https://github.com/pt9999/fixlang-minilib-json.git"
description = "Minilib: JSON encoder/decoder"

[[projects]]
name = "minilib-xml"
git = "https://github.com/pt9999/fixlang-minilib-xml.git"
description = "Minilib: XML encoder/decoder"
