all:

test:
	fix test

examples: ex-retained-ptr ex-typename ex-typed-ptr

ex-retained-ptr:
	fix run -f examples/retained_ptr_example.fix

ex-typename:
	fix run -f examples/typename_example.fix

ex-typed-ptr:
	fix run -f examples/typed_ptr_example.fix

