[general]
name = "minilib-tls"
version = "0.1.0"

[build]
files = [
    "lib/common/debug_log.fix",
    "lib/crypto/cert/asn1.fix",
    "lib/crypto/cert/asn1_der.fix",
    "lib/crypto/cert/asn1_der_encode.fix",
    "lib/crypto/cert/ca_certificates.fix",
    "lib/crypto/cert/cert_api.fix",
    "lib/crypto/cert/cert_api_default.fix",
    "lib/crypto/cert/cert_api_mock.fix",
    "lib/crypto/cert/crl.fix",
    "lib/crypto/cert/oid.fix",
    "lib/crypto/cert/pem.fix",
    "lib/crypto/cert/x509.fix",
    "lib/crypto/cert/x509_dns_name.fix",
    "lib/crypto/cert/x509_path.fix",
    "lib/crypto/cert/x509_policy.fix",
    "lib/crypto/cert/x509_signature.fix",
    "lib/crypto/cert/x509_time.fix",
    "lib/crypto/cipher/cipher_api.fix",
    "lib/crypto/cipher/cipher_api_default.fix",
    "lib/crypto/cipher/cipher_api_mock.fix",
    "lib/crypto/cipher/ec/ec_api.fix",
    "lib/crypto/cipher/ec/ec_api_default.fix",
    "lib/crypto/cipher/ec/ec_api_mock.fix",
    "lib/crypto/cipher/ec/ecdhe.fix",
    "lib/crypto/cipher/ec/ecdsa.fix",
    "lib/crypto/cipher/rsa/pkcs1.fix",
    "lib/crypto/cipher/rsa/rsa_api.fix",
    "lib/crypto/cipher/rsa/rsa_api_default.fix",
    "lib/crypto/cipher/rsa/rsa_api_mock.fix",
    "lib/crypto/cipher/rsa/rsa_private_key.fix",
    "lib/crypto/cipher/rsa/rsa_public_key.fix",
    "lib/crypto/tls/aead.fix",
    "lib/crypto/tls/alert.fix",
    "lib/crypto/tls/cipher_suite.fix",
    "lib/crypto/tls/ecdhe.fix",
    "lib/crypto/tls/extensions.fix",
    "lib/crypto/tls/handshake_protocol.fix",
    "lib/crypto/tls/handshake_state.fix",
    "lib/crypto/tls/hkdf.fix",
    "lib/crypto/tls/key_agreement.fix",
    "lib/crypto/tls/key_share.fix",
    "lib/crypto/tls/memory_bytes_io.fix",
    "lib/crypto/tls/protection.fix",
    "lib/crypto/tls/record_protocol.fix",
    "lib/crypto/tls/secret.fix",
    "lib/crypto/tls/tls_session.fix",
    "lib/crypto/tls/tls_session_mock.fix",
    "lib/crypto/tls/tls_socket.fix",
    "lib/crypto/tls/types.fix",
    "lib/monad/bytes_io.fix",
    "lib/math/montgomery.fix",
    "lib/net/http_client.fix",
    "lib/net/http_client/response_parser.fix",
]
opt_level = "default"

[build.test]
files = [
    "tests/test.fix"
]
opt_level = "default"


[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "asynctask"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-asynctask.git" }

[[dependencies]]
name = "hashmap"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }

[[dependencies]]
name = "random"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }

[[dependencies]]
name = "minilib-monad"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-monad.git" }

[[dependencies]]
name = "minilib-crypto"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-crypto.git" }

[[dependencies]]
name = "minilib-math"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-math.git" }

[[dependencies]]
name = "minilib-binary"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-binary.git" }

[[dependencies]]
name = "minilib-text"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-text.git" }

[[dependencies]]
name = "minilib-thread"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-thread.git" }

[[dependencies]]
name = "minilib-app"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-app.git" }

[[dependencies]]
name = "minilib-net"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-net.git" }

[[dependencies]]
name = "subprocess"
version = "1.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-subprocess.git" }