[general]
name = "minilib-math"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
    "lib/math/bigfloat.fix",
    "lib/math/bigint.fix",
    "lib/math/bigint_prime.fix",
    "lib/math/bignat.fix",
    "lib/math/complex.fix",
    "lib/math/euclid.fix",
    "lib/math/modular.fix",
    "lib/math/polynomial.fix",
    "lib/math/rational.fix",
    "lib/math/ring.fix",
    "lib/math/types.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/math/bigfloat_test.fix",
    "tests/math/bigint_prime_test.fix",
    "tests/math/bigint_test.fix",
    "tests/math/bignat_test.fix",
    "tests/math/complex_test.fix",
    "tests/math/euclid_test.fix",
    "tests/math/modular_test.fix",
    "tests/math/polynomial_test.fix",
    "tests/math/rational_test.fix",
    "tests/math/ring_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../fixlang-minilib-common"

[[dependencies]]
name = "minilib-binary"
version = "*"
path = "../fixlang-minilib-binary"

[[dependencies]]
name = "minilib-thread"
version = "*"
path = "../fixlang-minilib-thread"

[[dependencies]]
name = "math"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-math.git" }
