[general]
name = "minilib-thread"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
    "lib/thread/future.fix",
    "lib/thread/task_pool.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/thread/task_pool_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
# path = "../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-io"
version = "*"
# path = "../fixlang-minilib-io"
git = { url = "https://github.com/pt9999/fixlang-minilib-io.git" }

[[dependencies]]
name = "asynctask"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-asynctask.git" }
