[general]
name = "minilib-thread"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
    "lib/thread/future.fix",
    "lib/thread/task_pool.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/thread/task_pool_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../fixlang-minilib-common"

[[dependencies]]
name = "asynctask"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-asynctask.git" }
