[general]
name = "minilib-json"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
    "lib/encoding/json.fix",
    "lib/encoding/json/json_decoder.fix",
    "lib/encoding/json/json_encoder.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/encoding/json_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
# path = "../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-binary"
version = "*"
# path = "../fixlang-minilib-binary"
git = { url = "https://github.com/pt9999/fixlang-minilib-binary.git" }

[[dependencies]]
name = "minilib-text"
version = "*"
# path = "../fixlang-minilib-text"
git = { url = "https://github.com/pt9999/fixlang-minilib-text.git" }

[[dependencies]]
name = "minilib-collection"
version = "*"
# path = "../fixlang-minilib-collection"
git = { url = "https://github.com/pt9999/fixlang-minilib-collection.git" }
