all:

test: test-duality1 test-duality2 test-duality3 test-duality4

test-duality1:
	fix run -f duality_example1.fix -o a.out

test-duality2:
	fix run -f duality_example2.fix -o a.out

test-duality3:
	fix run -f duality_example3.fix -o a.out

test-duality4:
	fix run -f duality_example4.fix -o a.out
