all:

test: test-duality1 test-duality2 test-duality3

test-duality1:
	fix run -f duality_example1.fix -f dual.fix -f iostore.fix -o a.out

test-duality2:
	fix run -f duality_example2.fix -f dual.fix -f iostore.fix -o a.out

test-duality3:
	fix run -f duality_example3.fix -f dual.fix -f iostore.fix -o a.out

