[general]
name = "spell-checker"
version = "0.1.0"

[build]
output = "spell_checker.out"
opt_level = "separated"
files = [
    "spell_checker.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
# path = "../../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-app"
version = "*"
# path = "../../fixlang-minilib-app"
git = { url = "https://github.com/pt9999/fixlang-minilib-app.git" }

[[dependencies]]
name = "minilib-binary"
version = "*"
# path = "../../fixlang-minilib-binary"
git = { url = "https://github.com/pt9999/fixlang-minilib-binary.git" }

[[dependencies]]
name = "minilib-io"
version = "*"
# path = "../../fixlang-minilib-io"
git = { url = "https://github.com/pt9999/fixlang-minilib-io.git" }

[[dependencies]]
name = "character"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-character.git" }

[[dependencies]]
name = "hash"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hash.git" }

[[dependencies]]
name = "hashmap"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }

[[dependencies]]
name = "hashset"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashset.git" }