[general]
name = "minilib-media"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
    "lib/media/image.fix",
    "lib/media/png.fix",
    "lib/media/svg.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/media/svg_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
# path = "../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-io"
version = "*"
# path = "../fixlang-minilib-io"
git = { url = "https://github.com/pt9999/fixlang-minilib-io.git" }

[[dependencies]]
name = "minilib-xml"
version = "*"
# path = "../fixlang-minilib-xml"
git = { url = "https://github.com/pt9999/fixlang-minilib-xml.git" }
