[general]
name = "sample-client"
version = "0.1.0"

[build]
output = "sample_client.out"
opt_level = "separated"
files = [
    "sample_client.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
# path = "../../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-app"
version = "*"
# path = "../../fixlang-minilib-app"
git = { url = "https://github.com/pt9999/fixlang-minilib-app.git" }

[[dependencies]]
name = "minilib-net"
version = "*"
# path = "../../fixlang-minilib-net"
git = { url = "https://github.com/pt9999/fixlang-minilib-net.git" }
