[general]
name = "minilib-binary"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
    "lib/encoding/base64.fix",
    "lib/encoding/binary.fix",
    "lib/text/hex.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/encoding/base64_test.fix",
    "tests/encoding/binary_test.fix",
    "tests/text/hex_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../fixlang-minilib-common"
