[general]
name = "sandbox-math"
version = "0.1.0"

[build]
files = []
opt_level = "separated"


[[dependencies]]
name = "minilib-math"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-math.git" }

[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-text"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-text.git" }

[[dependencies]]
name = "minilib-monad"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-monad.git" }

[[dependencies]]
name = "math"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-math.git" }

[[dependencies]]
name = "character"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-character.git" }

[[dependencies]]
name = "hashmap"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }