[general]
name = "depgraph"
version = "0.3.0"
fix_version = "1.5.0"
authors = ["pt9999"]
license = "MIT"

[build]
files = [
    "main.fix",
    "depgraph.fix",
]
opt_level = "basic"


[[dependencies]]
name = "minilib-common"
version = ">=0.14.0"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-io"
version = ">=0.9.2"
git = { url = "https://github.com/pt9999/fixlang-minilib-io.git" }

[[dependencies]]
name = "minilib-monad"
version = ">=0.12.0"
git = { url = "https://github.com/pt9999/fixlang-minilib-monad.git" }

[[dependencies]]
name = "minilib-collection"
version = ">=0.9.1"
git = { url = "https://github.com/pt9999/fixlang-minilib-collection.git" }
