[general]
name = "minilib-text"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
    "lib/text/simple_parser.fix",
    "lib/text/unicode.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/text/simple_parser_test.fix",
    "tests/text/unicode_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../fixlang-minilib-common"
# git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }
