[general]
name = "probable-primes"
version = "0.1.0"

[build]
output = "probable_primes.out"
opt_level = "separated"
files = [
    "probable_primes.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../../fixlang-minilib-common"

[[dependencies]]
name = "minilib-app"
version = "*"
path = "../../fixlang-minilib-app"

[[dependencies]]
name = "minilib-math"
version = "*"
path = "../../fixlang-minilib-math"
