[general]
name = "probable-primes"
version = "0.1.0"

[build]
output = "probable_primes.out"
opt_level = "separated"
files = [
    "probable_primes.fix",
    "bigint_prime.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/bigint_prime_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../../fixlang-minilib-common"
# git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-app"
version = "*"
path = "../../fixlang-minilib-app"
# git = { url = "https://github.com/pt9999/fixlang-minilib-app.git" }

[[dependencies]]
name = "minilib-math"
version = "*"
path = "../../fixlang-minilib-math"
# git = { url = "https://github.com/pt9999/fixlang-minilib-math.git" }

[[dependencies]]
name = "minilib-thread"
version = "*"
path = "../../fixlang-minilib-thread"
# git = { url = "https://github.com/pt9999/fixlang-minilib-thread.git" }

