[general]
name = "sandbox-fp"
version = "0.1.0"

[build]
files = []
opt_level = "separated"

[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-monad"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-monad.git" }


[[dependencies]]
name = "hash"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hash.git" }

[[dependencies]]
name = "hashmap"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }

[[dependencies]]
name = "minilib-comonad"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-comonad.git" }