all:

test:
	fix run -f applicative.fix
	fix run -f denotation.fix
	fix run -f free_monad.fix
	fix run -f lens.fix
	fix run -f monad1.fix
	#fix run -f monoid_ex.fix monoid_test1.fix
	fix run -f option_t.fix
	fix run -f reader_writer_test.fix
	fix run -f state_monad_test2.fix
