[general]
name = "minilib-app"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
    "lib/app/clap.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/app/clap_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../fixlang-minilib-common"
# git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }


[[dependencies]]
name = "hashmap"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }