[general]
name = "minilib-xml"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
    "lib/encoding/xml.fix",
    "lib/encoding/xml/xml_helpers.fix",
    "lib/encoding/xml/xml_parser.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/encoding/xml/xml_helpers_test.fix",
    "tests/encoding/xml/xml_parser_test.fix",
    "tests/encoding/xml_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
# path = "../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-text"
version = "*"
# path = "../fixlang-minilib-text"
git = { url = "https://github.com/pt9999/fixlang-minilib-text.git" }

[[dependencies]]
name = "minilib-binary"
version = "*"
# path = "../fixlang-minilib-binary"
git = { url = "https://github.com/pt9999/fixlang-minilib-binary.git" }
