[general]
name = "fractal-server"
version = "0.1.0"

[build]
output = "fractal_server.out"
opt_level = "separated"
files = [
    "fractal_server.fix",
]
dynamic_links = ["png"]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../../fixlang-minilib-common"

[[dependencies]]
name = "minilib-app"
version = "*"
path = "../../fixlang-minilib-app"

[[dependencies]]
name = "minilib-net"
version = "*"
path = "../../fixlang-minilib-net"

[[dependencies]]
name = "minilib-media"
version = "*"
path = "../../fixlang-minilib-media"

[[dependencies]]
name = "minilib-math"
version = "*"
path = "../../fixlang-minilib-math"

[[dependencies]]
name = "minilib-io"
version = "*"
path = "../../fixlang-minilib-io"

[[dependencies]]
name = "minilib-thread"
version = "*"
path = "../../fixlang-minilib-thread"

[[dependencies]]
name = "asynctask"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-asynctask.git" }
