[general]
name = "minilib-monad"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
"lib/monad/cont.fix",
"lib/monad/error.fix",
"lib/monad/except.fix",
"lib/monad/identity.fix",
"lib/monad/io.fix",
"lib/monad/reader.fix",
"lib/monad/state.fix",
"lib/monad/trans.fix",
"lib/monad/writer.fix",
"lib/trait/monoid.fix",
"lib/trait/semigroup.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/monad/cont_test.fix",
    "tests/monad/error_test.fix",
    "tests/monad/except_test.fix",
    "tests/monad/identity_test.fix",
    "tests/monad/io_test.fix",
    "tests/monad/reader_test.fix",
    "tests/monad/state_test.fix",
    "tests/monad/writer_test.fix",
    "tests/trait/monoid_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
# path = "../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }
