[general]
name = "sample-server"
version = "0.1.0"

[build]
output = "sample_server.out"
opt_level = "separated"
files = [
    "sample_server.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../../fixlang-minilib-common"

[[dependencies]]
name = "minilib-app"
version = "*"
path = "../../fixlang-minilib-app"

[[dependencies]]
name = "minilib-net"
version = "*"
path = "../../fixlang-minilib-net"
