[general]
name = "sandbox-crypto"
version = "0.1.0"
authors = ["pt9999"]
license = "MIT"

[build]
opt_level = "separated"
files = [
]

[build.test]
opt_level = "separated"
files = [
]


[[dependencies]]
name = "minilib-crypto"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-crypto.git" }


[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }


[[dependencies]]
name = "minilib-monad"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-monad.git" }

[[dependencies]]
name = "asynctask"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-asynctask.git" }