all:

test:
	fix run -f aes_gcm_test1.fix
	fix run -f aes_gcmvs.fix
	fix run -f aes_test1.fix
	fix run -f cipher_test1.fix cipher.fix
	fix run -f md5_test1.fix
	fix run -f pkcs5_test1.fix
	fix run -f secure_random_test1.fix
