[general]
name = "sandbox-terminal"
version = "0.1.0"

[build]
files = [
    "terminal.fix",
]
opt_level = "separated"

[[dependencies]]
name = "minilib-common"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-monad"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-monad.git" }


[[dependencies]]
name = "minilib-io"
version = "*"
git = { url = "https://github.com/pt9999/fixlang-minilib-io.git" }

