[general]
name = "minilib-crypto"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
    "lib/crypto/aes.fix",
    "lib/crypto/aes/aes_gcm.fix",
    "lib/crypto/hmac.fix",
    "lib/crypto/hmac/hmac_md5.fix",
    "lib/crypto/hmac/hmac_sha1.fix",
    "lib/crypto/hmac/hmac_sha256.fix",
    "lib/crypto/md5.fix",
    "lib/crypto/secure_random.fix",
    "lib/crypto/sha1.fix",
    "lib/crypto/sha256.fix",
    "lib/crypto/sha512.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/crypto/aes/aes_gcm_test.fix",
    "tests/crypto/aes_test.fix",
    "tests/crypto/hmac_test.fix",
    "tests/crypto/md5_test.fix",
    "tests/crypto/sha1_test.fix",
    "tests/crypto/sha256_test.fix",
    "tests/crypto/sha512_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../fixlang-minilib-common"

[[dependencies]]
name = "minilib-binary"
version = "*"
path = "../fixlang-minilib-binary"
