[general]
name = "minilib-comonad"
version = "0.1.0"

[build]
opt_level = "separated"
files = [
    "lib/comonad/env.fix",
    "lib/comonad/identity_c.fix",
    "lib/comonad/traced.fix",
    "lib/trait/comonad.fix",
]

[build.test]
opt_level = "separated"
files = [
    "tests/test.fix",
    "tests/comonad/env_test.fix",
    "tests/comonad/identity_c_test.fix",
    "tests/comonad/traced_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../fixlang-minilib-common"

[[dependencies]]
name = "minilib-monad"
version = "*"
path = "../fixlang-minilib-monad"
