[general]
name = "grep"
version = "0.1.0"

[build]
output = "grep.out"
opt_level = "separated"
files = [
    "grep.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../../fixlang-minilib-common"

[[dependencies]]
name = "minilib-app"
version = "*"
path = "../../fixlang-minilib-app"

[[dependencies]]
name = "minilib-regexp"
version = "*"
path = "../../fixlang-minilib-regexp"
