[general]
name = "grep"
version = "0.1.0"

[build]
output = "grep.out"
opt_level = "separated"
files = [
    "grep.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
# path = "../../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-app"
version = "*"
# path = "../../fixlang-minilib-app"
git = { url = "https://github.com/pt9999/fixlang-minilib-app.git" }

[[dependencies]]
name = "minilib-regexp"
version = "*"
# path = "../../fixlang-minilib-regexp"
git = { url = "https://github.com/pt9999/fixlang-minilib-regexp.git" }
