[general]
name = "sudoku"
version = "0.1.0"

[build]
output = "sudoku.out"
opt_level = "separated"
files = [
    "sudoku.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
path = "../../fixlang-minilib-common"

[[dependencies]]
name = "minilib-app"
version = "*"
path = "../../fixlang-minilib-app"

[[dependencies]]
name = "minilib-xml"
version = "*"
path = "../../fixlang-minilib-xml"

[[dependencies]]
name = "minilib-media"
version = "*"
path = "../../fixlang-minilib-media"

[[dependencies]]
name = "asynctask"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-asynctask.git" }

[[dependencies]]
name = "random"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }

[[dependencies]]
name = "time"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-time.git" }