name: test-crypto
on:
  workflow_dispatch:

jobs:
  test_crypto:
    name: Test Crypto Job
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: Run tests
      run: docker run --pull always --rm -v .:/work -w /work pt9999/fixlang_minilib_ci make test-crypto

