name: test
on:
  workflow_dispatch:

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: List directory
      run: ls -l

    - name: Run tests
      run: docker run --rm -v .:/work -w /work pt9999/fix:latest make test

    - name: Make examples
      run: docker run --rm -v .:/work -w /work pt9999/fix:latest make examples
