name: test-crypto
on:
  workflow_dispatch:

jobs:
  test_crypto:
    name: Test Crypto Job
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: 'recursive'

    - name: Pull the docker image for CI
      run: docker pull pt9999/fixlang_minilib_ci

    - name: Run test codes
      run: docker run --rm -v .:/work -w /work pt9999/fixlang_minilib_ci make test -C _sandbox/crypto/fixlang-minilib-tls

    - name: Build example programs
      run: docker run --rm -v .:/work -w /work pt9999/fixlang_minilib_ci make examples -C _sandbox/crypto/fixlang-minilib-tls
