name: test
on:
  workflow_dispatch:

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: 'recursive'

    - name: List directory
      run: ls -la _projects

    - name: Pull the docker image for CI
      run: docker pull pt9999/fixlang_minilib_ci

    - name: Run test codes
      run: docker run --rm -v .:/work -w /work pt9999/fixlang_minilib_ci make test -C _projects

    - name: Build example programs
      run: docker run --rm -v .:/work -w /work pt9999/fixlang_minilib_ci make examples -C _projects
