name: test
on:
  workflow_dispatch:

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: 'recursive'

    - name: List directory
      run: ls -la _projects

    - name: Run tests and make examples
      run: docker run --pull always --rm -v .:/work -w /work pt9999/fixlang_minilib_ci make test -C _projects
